version: '2'
services:
  redis:
    image: redis
    container_name: bigdata_redis
    ports:
      - "6379:6379"
    networks:
      - dp-server

  dp-express:
    build: .
    image: dp-image
    container_name: dp_express
    ports:
      - "18080:80"
    links:
      - redis
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - dp-server

networks:
  dp-server:
    driver: bridge
